name: shopping_list
description: Simple Shopping List

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.8
  fluttertoast: ^8.0.8
  flutter_typeahead: ^3.2.1
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.2
flutter_native_splash:
  color: "#FFFFFF"
  image: assets\icon.png
  android: true
  ios: true
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  #flutter pub run flutter_launcher_icons:main

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
